version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/todo
      NODE_ENV: development
    depends_on:
      - postgres
    command: sh -c "npm run migrate && npm start"
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    environment:
      VITE_API_URL: http://localhost:3001/api
    depends_on:
      - server
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules 

volumes:
  postgres_data: